# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_name', models.CharField(default='', max_length=50, verbose_name='\u4f5c\u8005')),
                ('title', models.CharField(default='', max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.CharField(default='', max_length=500, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u603b\u7ed3\u4fe1\u606f\u586b\u62a5',
                'verbose_name_plural': '\u603b\u7ed3\u4fe1\u606f\u586b\u62a5',
            },
        ),
    ]
